### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by roaris** [roaris/algo-library#1]
## Data Structure
- [ ] Unionfind
- [ ] Binary Indexed Tree
- [ ] Segment Tree
- [ ] Lazy Segment Tree
- [ ] Sparse Table
- [ ] Accumulate 2D
- [ ] Convex Full Trick (Monotone)
- [ ] Dancing Links

## Graph
- [ ] Dijkstra
- [ ] Bellman Ford
- [ ] Warshall Floyd
- [ ] Ford Fulkerson
- [ ] Dinic
- [ ] Min Cost Flow
- [ ] Strongly Connected Component
- [ ] Lowest Common Ancestor
- [ ] Heavy Light Decomposition

## Math
- [ ] Divisors
- [ ] Eratosthenes
- [ ] Factorize
- [ ] Smallest Prime Factor
- [ ] Combinatorics
- [ ] Matrix Pow
- [ ] Xor Base
- [ ] Baby Step Giant Step
- [ ] 2-SAT

## String
- [ ] Rolling Hash
- [ ] Trie
- [ ] Z Algorithm
- [ ] Manachar
- [ ] KMP
- [ ] Suffix Array

## Misc
- [ ] Compress
- [ ] Mo's Algorithm
